all: 
	swiftc alter-date-format.swift
	./alter-date-format < input.txt > output.txt
	open output.txt

edit:
	vi alter-date-format.swift

make:
	vi Makefile

input:
	vi input.txt

output:
	open output.txt

