# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AsyncUnitTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Quick'
  pod 'Nimble'
  pod 'EarlGrey'

  # Pods for AsyncUnitTest

  target 'AsyncUnitTestTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
    pod 'EarlGrey'

  end

end
