# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'facebookLoginStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

  # Pods for facebookLoginStudy

end
