# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WithInnoTest_Sungeun' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'R.swift'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 5.0'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Toaster', '~> 2.2.0'
  

  # Pods for WithInnoTest_Sungeun

end
