all: 
	swiftc is-available-time.swift
	./is-available-time < input.txt > output.txt
	open output.txt

edit:
	vi is-available-time.swift

make:
	vi Makefile

input:
	vi input.txt

output:
	open output.txt

